### ISSUE TITLE
Broken Shift-JS filenames

### ISSUE THREAD

**Issue by Minty-Meeo** [AxioDL/nod#15]
Extracting ISOs with Shift-JS filepaths will result in gibberish, such as "�X�i�b�v�V���b�ggameConfig.ini".  Pikmin 2 (GCN) is a good example.  I am currently using the v1 release of nodtool, but I doesn't appear any commits since that release have fixed this.

I recommend converting filepaths between Shift-JS and UTF-8 Like how Dolphin Emulator does (in Core\DiscIO\FileSystemGCWii.cpp)

**Comment by Antidote** [comment]
I'll take a look at that and see what I can do, unfortunately I don't have a copy of Pikmin 2 to test.

**Comment by Antidote** [comment]
Can you get me a dump of the FST? I can use that to test, I don't need any of the data to go along with it.

**Comment by Minty-Meeo** [comment]
[fst.zip](https://github.com/AxioDL/nod/files/5360602/fst.zip)

[do not link to copyrighted material]

**Comment by Antidote** [comment]
I'm not done yet, but I've made some progress
`プロダクトgameConfig.ini`

**Comment by Minty-Meeo** [comment]
I did it myself.
https://github.com/AxioDL/nod/pull/16
